spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 0

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消息确认机制
    publisher-confirm-type: correlated
    publisher-returns: true
    # 连接池配置
    connection-timeout: 5000
    cache:
      channel:
        size: 50

  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /seckill
  # 线程池配置
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 20000

# 秒杀相关配置
seckill:
  # Redis key前缀
  redis-key-prefix:
    stock: "seckill:stock:"
    user-record: "seckill:user:"
    activity: "seckill:activity:"
    product: "seckill:product:"
  # 库存预热配置
  prewarm:
    enabled: true
    time-before-start: 600000  # 提前10分钟预热
  # 异步处理配置
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
  # 接口限流配置
  rate-limit:
    enabled: true
    token-rate: 10000  # 令牌生成速率（每秒）
    capacity: 50000    # 令牌桶容量

# 日志配置
logging:
  level:
    root: INFO
    com.example.seckill: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/seckill.log
    max-history: 7
    max-size: 10MB

# Resilience4j配置
resilience4j:
  # 限流配置
  ratelimiter:
    instances:
      default:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 500ms
  # 断路器配置
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000ms
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
  # 重试配置
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 100ms
        exponential-backoff-multiplier: 2.0