spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://mysql:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis配置
  redis:
    host: redis
    port: 6379
    database: 0
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 0

  # RabbitMQ配置
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 消息确认机制
    publisher-confirm-type: correlated
    publisher-returns: true

  # 服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: public
        group: DEFAULT_GROUP

  # Seata配置
  seata:
    enabled: true
    tx-service-group: my_test_tx_group
    registry:
      type: nacos
      nacos:
        application: seata-server
        server-addr: nacos:8848
        namespace: public
    config:
      type: nacos
      nacos:
        server-addr: nacos:8848
        namespace: public
        group: SEATA_GROUP

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /seckill

# 秒杀相关配置
seckill:
  # Redis key前缀
  redis-key-prefix:
    stock: "seckill:stock:"
    user-record: "seckill:user:"
    activity: "seckill:activity:"
    product: "seckill:product:"
  # 库存预热配置
  prewarm:
    enabled: true
    time-before-start: 600000  # 提前10分钟预热
  # 异步处理配置
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
  # 接口限流配置
  rate-limit:
    enabled: true
    token-rate: 10000  # 令牌生成速率（每秒）
    capacity: 50000    # 令牌桶容量