server:
  port: 8080
  servlet:
    context-path: /user-center

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 3000ms

# JWT配置
jwt:
  secret: sso-server-secret-key-1234567890abcdefghijklmnopqrstuvwxyz
  expiration: 7200000  # 2小时
  refresh-expiration: 2592000000  # 30天

# 自定义配置
custom:
  sso:
    login-page: /login
    token-header: Authorization
    token-prefix: Bearer